#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: media_media mixerengine_mixerengine ffmpeg_ffmpeg mixertest_mixertest

media_media: 
	$(MAKE) -C media all -f media.cbp.mak

mixerengine_mixerengine: media_media
	$(MAKE) -C mixerEngine all -f mixerEngine.cbp.mak

ffmpeg_ffmpeg: media_media
	$(MAKE) -C ffmpeg all -f ffmpeg.cbp.mak

mixertest_mixertest: mixerengine_mixerengine
	$(MAKE) -C mixerTest all -f mixerTest.cbp.mak

clean: clean_media_media clean_mixerengine_mixerengine clean_ffmpeg_ffmpeg clean_mixertest_mixertest

clean_media_media: 
	$(MAKE) -C media clean -f media.cbp.mak

clean_mixerengine_mixerengine: 
	$(MAKE) -C mixerEngine clean -f mixerEngine.cbp.mak

clean_ffmpeg_ffmpeg: 
	$(MAKE) -C ffmpeg clean -f ffmpeg.cbp.mak

clean_mixertest_mixertest: 
	$(MAKE) -C mixerTest clean -f mixerTest.cbp.mak

.PHONY: clean_media_media clean_mixerengine_mixerengine clean_ffmpeg_ffmpeg clean_mixertest_mixertest

